#ifndef UNITY_CONFIG_H
#define UNITY_CONFIG_H

#define UNITY_SUPPORT_64
#define UNITY_OUTPUT_COLOR
#define UNITY_INCLUDE_DOUBLE
#define UNITY_INCLUDE_PRINT_FORMATTED
#define UNITY_FIXTURE_NO_EXTRAS

#endif
